# Generated by Django 3.2.7 on 2021-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='metode',
            field=models.CharField(choices=[('Mandiri', 'Mandiri Virtual Account'), ('BCA', 'BCA Virtual Account'), ('BankBCA', 'Bank BCA'), ('BankMANDIRI', 'Bank MANDIRI')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='durasi',
            field=models.CharField(choices=[('Next Day', 'Next Day (1 hari)'), ('Reguler', 'Reguler (2-4 hari)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pengiriman',
            name='kurir',
            field=models.CharField(choices=[('AnterAja', 'AnterAja'), ('Tiki', 'Tiki'), ('JNE', 'JNE')], max_length=100),
        ),
    ]
