# Generated by Django 3.2.7 on 2021-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_page', '0003_auto_20211030_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='telp',
            field=models.BigIntegerField(),
        ),
    ]
