# Generated by Django 3.2.7 on 2021-10-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], max_length=1)),
                ('size', models.CharField(choices=[('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=2)),
                ('model', models.CharField(choices=[('surgical', 'SURGICAL'), ('sponge', 'SPONGE'), ('pitta', 'PITTA'), ('cloth', 'CLOTH')], max_length=8)),
                ('style', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
