# Generated by Django 3.2.7 on 2021-10-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0002_auto_20211028_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='model',
            field=models.CharField(choices=[('SURGICAL', 'surgical'), ('SPONGE', 'sponge'), ('PITTA', 'pitta'), ('CLOTH', 'cloth')], max_length=8),
        ),
        migrations.AlterField(
            model_name='custommask',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unisex')], max_length=1),
        ),
        migrations.AlterField(
            model_name='custommask',
            name='size',
            field=models.CharField(choices=[('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=2),
        ),
    ]
