# Generated by Django 3.2.7 on 2021-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0005_auto_20211028_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='model',
            field=models.CharField(choices=[('SURGICAL', 'Surgical'), ('SPONGE', 'Sponge'), ('PITTA', 'Pitta'), ('CLOTH', 'Cloth')], default=None, max_length=8),
        ),
    ]
