# Generated by Django 3.2.7 on 2021-10-30 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_page', '0001_initial'),
        ('cuztomize_masker_page', '0008_auto_20211029_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_cart_page.order'),
        ),
        migrations.AlterField(
            model_name='custommask',
            name='style',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
