# Generated by Django 3.2.7 on 2021-10-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0008_auto_20211028_2207'),
        ('cuztomize_masker_page', '0009_auto_20211030_1025'),
    ]

    operations = [
    ]
