# Generated by Django 3.2.7 on 2021-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0010_merge_0008_auto_20211028_2207_0009_auto_20211030_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='price',
            field=models.FloatField(default=15),
        ),
    ]
