# Generated by Django 3.2.7 on 2021-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0011_alter_custommask_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='style',
            field=models.FileField(blank=True, null=True, upload_to='custom-mask-style/'),
        ),
    ]
