# Generated by Django 3.2.7 on 2021-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0012_alter_custommask_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='style',
            field=models.FileField(default=None, upload_to='custom-mask-style/'),
        ),
    ]
