# Generated by Django 3.2.7 on 2021-11-05 08:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuztomize_masker_page', '0013_alter_custommask_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommask',
            name='style',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
    ]
