# Generated by Django 3.1.5 on 2021-10-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkmasker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
