# Generated by Django 3.2.7 on 2021-10-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkmasker',
            name='image',
        ),
    ]
