# Generated by Django 3.2.7 on 2021-10-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list_page', '0002_remove_produkmasker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkmasker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
