# Generated by Django 3.2.7 on 2021-11-04 21:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list_page', '0005_produkmasker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkmasker',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
