# Generated by Django 3.1.5 on 2021-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list_page', '0005_produkmasker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkmasker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
