# Generated by Django 3.2.7 on 2021-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_subscribedemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedemail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
