# Generated by Django 3.2.7 on 2021-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_alter_subscribedemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedemail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
